# Generated by Django 3.2.23 on 2024-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0002_auto_20240919_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
