# Generated by Django 3.2.23 on 2024-09-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0006_auto_20240929_0304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archivo',
            new_name='File',
        ),
    ]
