# Generated by Django 3.2.23 on 2024-10-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0007_rename_archivo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividad_preguntas',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='respuesta_correcta',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickrecap_app.actividad'),
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('correcta', models.BooleanField(default=False)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickrecap_app.pregunta')),
            ],
        ),
    ]
