# Generated by Django 3.2.23 on 2024-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0009_auto_20241001_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='flashcard_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.TextField(),
        ),
    ]
