# Generated by Django 3.2.23 on 2024-10-12 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0012_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='usuario',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
