# Generated by Django 3.2.23 on 2024-10-12 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0013_auto_20241011_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
