# Generated by Django 3.2.23 on 2024-10-12 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0014_alter_comments_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
