# Generated by Django 3.2.23 on 2024-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0018_alter_gaprespuesta_opciones_correctas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapenunciado',
            name='alternativas_incorrectas',
            field=models.TextField(default='hola'),
        ),
    ]
