# Generated by Django 3.2.23 on 2024-10-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0020_alter_gapenunciado_alternativas_incorrectas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField()),
                ('commentary', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='favorito',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='rated',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.AddField(
            model_name='rated',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickrecap_app.actividad'),
        ),
        migrations.AddField(
            model_name='rated',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickrecap_app.actividad'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
