# Generated by Django 3.2.23 on 2024-11-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickrecap_app', '0022_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.TextField(),
        ),
    ]
